/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.LongConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class BasicInfo {

	@NotNull
	@Min(1L) @Max(2L)
	@Component(0)
	public Integer dataDirect;

	@NotNull
	@Min(0L) @Max(4294967295L)
	@Component(1)
	public Long dataSN;

	@NotNull
	@Min(0L) @Max(4294967295L)
	@Component(2)
	public Long timeSec;

	@NotNull
	@Min(0L) @Max(999L)
	@Component(3)
	public Integer timeMsec;


	public boolean equals(Object obj) {
		if(!(obj instanceof BasicInfo)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static BasicInfo der_decode(InputStream in) throws IOException {
		return (BasicInfo)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65537);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(BasicInfo.class);
		AsnConverter dataDirectConverter = IntegerConverter.INSTANCE;
		AsnConverter dataSNConverter = LongConverter.INSTANCE;
		AsnConverter timeSecConverter = LongConverter.INSTANCE;
		AsnConverter timeMsecConverter = IntegerConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { dataDirectConverter, dataSNConverter, timeSecConverter, timeMsecConverter });
	}


}
