/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.BooleanConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.VectorConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class BoundData {

	@NotNull
	@Component(0)
	public Boolean boundInOut;

	@NotNull
	@Size(min=1, max=127)
	@Component(1)
	public Vector<LongiLatiTude> boundTude;


	public boolean equals(Object obj) {
		if(!(obj instanceof BoundData)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static BoundData der_decode(InputStream in) throws IOException {
		return (BoundData)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65544);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(BoundData.class);
		AsnConverter boundInOutConverter = BooleanConverter.INSTANCE;
		AsnConverter boundTudeConverter = new VectorConverter(LongiLatiTude.CONV);
		CONV.setComponentConverters(new AsnConverter[] { boundInOutConverter, boundTudeConverter });
	}


}
