/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.OctetStringConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class CustName {

	@NotNull
	@Size(min=1, max=32)
	@Component(0)
	public byte[] ecuName;

	@NotNull
	@Size(min=1, max=64)
	@Component(1)
	public byte[] sigName;

	@NotNull
	@Size(min=1, max=64)
	@Component(2)
	public byte[] sigUnit;


	public boolean equals(Object obj) {
		if(!(obj instanceof CustName)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static CustName der_decode(InputStream in) throws IOException {
		return (CustName)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65552);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(CustName.class);
		AsnConverter ecuNameConverter = OctetStringConverter.INSTANCE;
		AsnConverter sigNameConverter = OctetStringConverter.INSTANCE;
		AsnConverter sigUnitConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { ecuNameConverter, sigNameConverter, sigUnitConverter });
	}


}
