/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.OctetStringConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class CustNameReq {

	@NotNull
	@Size(min=16, max=16)
	@Component(0)
	public byte[] dbcMD5;

	@NotNull
	@Min(0L) @Max(999L)
	@Component(1)
	public Integer startNo;

	@NotNull
	@Min(0L) @Max(999L)
	@Component(2)
	public Integer endNo;


	public boolean equals(Object obj) {
		if(!(obj instanceof CustNameReq)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static CustNameReq der_decode(InputStream in) throws IOException {
		return (CustNameReq)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65548);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(CustNameReq.class);
		AsnConverter dbcMD5Converter = OctetStringConverter.INSTANCE;
		AsnConverter startNoConverter = IntegerConverter.INSTANCE;
		AsnConverter endNoConverter = IntegerConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { dbcMD5Converter, startNoConverter, endNoConverter });
	}


}
