/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import org.asnlab.asndt.runtime.conv.AnnotationChoiceConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.ChoiceConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Alternative;
import org.asnlab.asndt.runtime.type.AsnType;

public class EventReport {

	public static final int faultReportChosen = 0;

	public final int choiceID;

	@Alternative(0)
	public final FaultStruct faultReport;


	private EventReport(int choiceID, FaultStruct faultReport) {
		this.choiceID = choiceID;
		this.faultReport = faultReport;
	}

	public static EventReport faultReport(FaultStruct faultReport) {
		return new EventReport(faultReportChosen, faultReport);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof EventReport)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static EventReport der_decode(InputStream in) throws IOException {
		return (EventReport)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65571);

	public final static ChoiceConverter CONV;

	static {
		CONV = new AnnotationChoiceConverter(EventReport.class);
		AsnConverter faultReportConverter = FaultStruct.CONV;
		CONV.setAlternativeConverters(new AsnConverter[] { faultReportConverter });
	}


}
