/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.LongConverter;
import org.asnlab.asndt.runtime.conv.OctetStringConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class FaultData {

	@NotNull
	@Min(1L) @Max(3L)
	@Component(0)
	public Integer vfFlag;

	@NotNull
	@Min(0L) @Max(4294967295L)
	@Component(1)
	public Long vfStartSec;

	@NotNull
	@Min(0L) @Max(4294967295L)
	@Component(2)
	public Long vfEndSec;

	@NotNull
	@Component(3)
	public byte[] vfCode;


	public boolean equals(Object obj) {
		if(!(obj instanceof FaultData)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static FaultData der_decode(InputStream in) throws IOException {
		return (FaultData)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65569);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(FaultData.class);
		AsnConverter vfFlagConverter = IntegerConverter.INSTANCE;
		AsnConverter vfStartSecConverter = LongConverter.INSTANCE;
		AsnConverter vfEndSecConverter = LongConverter.INSTANCE;
		AsnConverter vfCodeConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { vfFlagConverter, vfStartSecConverter, vfEndSecConverter, vfCodeConverter });
	}


}
