/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import org.asnlab.asndt.runtime.conv.AnnotationChoiceConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.ChoiceConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Alternative;
import org.asnlab.asndt.runtime.type.AsnType;

public class FileTrans {

	public static final int imgDownloadChosen = 0;
	public static final int dbcDownloadChosen = 1;

	public final int choiceID;

	@Alternative(0)
	public final ImgDownload imgDownload;

	@Alternative(1)
	public final DBCDownload dbcDownload;


	private FileTrans(int choiceID, ImgDownload imgDownload, DBCDownload dbcDownload) {
		this.choiceID = choiceID;
		this.imgDownload = imgDownload;
		this.dbcDownload = dbcDownload;
	}

	public static FileTrans imgDownload(ImgDownload imgDownload) {
		return new FileTrans(imgDownloadChosen, imgDownload, null);
	}

	public static FileTrans dbcDownload(DBCDownload dbcDownload) {
		return new FileTrans(dbcDownloadChosen, null, dbcDownload);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof FileTrans)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static FileTrans der_decode(InputStream in) throws IOException {
		return (FileTrans)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65576);

	public final static ChoiceConverter CONV;

	static {
		CONV = new AnnotationChoiceConverter(FileTrans.class);
		AsnConverter imgDownloadConverter = ImgDownload.CONV;
		AsnConverter dbcDownloadConverter = DBCDownload.CONV;
		CONV.setAlternativeConverters(new AsnConverter[] { imgDownloadConverter, dbcDownloadConverter });
	}


}
