/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

import org.asnlab.asndt.runtime.conv.AnnotationChoiceConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.ChoiceConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.annotation.Alternative;
import org.asnlab.asndt.runtime.type.AsnType;

public class ImgDownload {

	public static final int imgDownReqChosen = 0;
	public static final int imgDownRspChosen = 1;

	public final int choiceID;

	@Alternative(0)
	public final ImgDownReq imgDownReq;

	@Min(0L) @Max(5L)
	@Alternative(1)
	public final Integer imgDownRsp;


	private ImgDownload(int choiceID, ImgDownReq imgDownReq, Integer imgDownRsp) {
		this.choiceID = choiceID;
		this.imgDownReq = imgDownReq;
		this.imgDownRsp = imgDownRsp;
	}

	public static ImgDownload imgDownReq(ImgDownReq imgDownReq) {
		return new ImgDownload(imgDownReqChosen, imgDownReq, null);
	}

	public static ImgDownload imgDownRsp(Integer imgDownRsp) {
		return new ImgDownload(imgDownRspChosen, null, imgDownRsp);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof ImgDownload)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static ImgDownload der_decode(InputStream in) throws IOException {
		return (ImgDownload)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65573);

	public final static ChoiceConverter CONV;

	static {
		CONV = new AnnotationChoiceConverter(ImgDownload.class);
		AsnConverter imgDownReqConverter = ImgDownReq.CONV;
		AsnConverter imgDownRspConverter = IntegerConverter.INSTANCE;
		CONV.setAlternativeConverters(new AsnConverter[] { imgDownReqConverter, imgDownRspConverter });
	}


}
