/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class IntRsp {

	@NotNull
	@Min(0L) @Max(65535L)
	@Component(0)
	public Integer dataInterval;

	@NotNull
	@Min(50L) @Max(150L)
	@Component(1)
	public Integer heartInterval;


	public boolean equals(Object obj) {
		if(!(obj instanceof IntRsp)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static IntRsp der_decode(InputStream in) throws IOException {
		return (IntRsp)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65540);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(IntRsp.class);
		AsnConverter dataIntervalConverter = IntegerConverter.INSTANCE;
		AsnConverter heartIntervalConverter = IntegerConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { dataIntervalConverter, heartIntervalConverter });
	}


}
