/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.NotNull;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.BooleanConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.DoubleConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class LongiLatiTude {

	@NotNull
	@Component(0)
	public Boolean isEast;

	@NotNull
	@Component(1)
	public Double longitude;

	@NotNull
	@Component(2)
	public Boolean isNorth;

	@NotNull
	@Component(3)
	public Double latitude;


	public boolean equals(Object obj) {
		if(!(obj instanceof LongiLatiTude)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static LongiLatiTude der_decode(InputStream in) throws IOException {
		return (LongiLatiTude)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65542);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(LongiLatiTude.class);
		AsnConverter isEastConverter = BooleanConverter.INSTANCE;
		AsnConverter longitudeConverter = DoubleConverter.INSTANCE;
		AsnConverter isNorthConverter = BooleanConverter.INSTANCE;
		AsnConverter latitudeConverter = DoubleConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { isEastConverter, longitudeConverter, isNorthConverter, latitudeConverter });
	}


}
