/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.BooleanConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.LongConverter;
import org.asnlab.asndt.runtime.conv.OctetStringConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class ParaSetReq {

	@Null
	@Component(0)
	public IntRsp intSet;	/* OPTIONAL */

	@Null
	@Component(1)
	public LinkRsp link1Set;	/* OPTIONAL */

	@Null
	@Component(2)
	public LinkRsp link2Set;	/* OPTIONAL */

	@Null
	@Component(3)
	public Boolean link2EnSet;	/* OPTIONAL */

	@Null
	@Size(min=17, max=17)
	@Component(4)
	public byte[] vinSet;	/* OPTIONAL */

	@Null
	@Component(5)
	public DestRsp destSet;	/* OPTIONAL */

	@Null
	@Component(6)
	public BoundData boundSet;	/* OPTIONAL */

	@Null
	@Component(7)
	public byte[] dbcNameSet;	/* OPTIONAL */

	@Null
	@Component(8)
	public Long sysSet;	/* OPTIONAL */

	@Null
	@Min(1L) @Max(100L)
	@Component(9)
	public Integer sdHzSet;	/* OPTIONAL */

	@Null
	@Component(10)
	public byte[] authKeySet;	/* OPTIONAL */

	@Null
	@Component(11)
	public CommInt commIntSet;	/* OPTIONAL */

	@Null
	@Min(0L) @Max(1L)
	@Component(12)
	public Integer canlogModeSet;	/* OPTIONAL */

	@Null
	@Component(13)
	public Long canlogTimeSet;	/* OPTIONAL */


	public boolean equals(Object obj) {
		if(!(obj instanceof ParaSetReq)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static ParaSetReq der_decode(InputStream in) throws IOException {
		return (ParaSetReq)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65546);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(ParaSetReq.class);
		AsnConverter intSetConverter = IntRsp.CONV;
		AsnConverter link1SetConverter = LinkRsp.CONV;
		AsnConverter link2SetConverter = LinkRsp.CONV;
		AsnConverter link2EnSetConverter = BooleanConverter.INSTANCE;
		AsnConverter vinSetConverter = OctetStringConverter.INSTANCE;
		AsnConverter destSetConverter = DestRsp.CONV;
		AsnConverter boundSetConverter = BoundData.CONV;
		AsnConverter dbcNameSetConverter = OctetStringConverter.INSTANCE;
		AsnConverter sysSetConverter = LongConverter.INSTANCE;
		AsnConverter sdHzSetConverter = IntegerConverter.INSTANCE;
		AsnConverter authKeySetConverter = OctetStringConverter.INSTANCE;
		AsnConverter commIntSetConverter = CommInt.CONV;
		AsnConverter canlogModeSetConverter = IntegerConverter.INSTANCE;
		AsnConverter canlogTimeSetConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { intSetConverter, link1SetConverter, link2SetConverter, link2EnSetConverter, vinSetConverter, destSetConverter, boundSetConverter, dbcNameSetConverter, sysSetConverter, sdHzSetConverter, authKeySetConverter, commIntSetConverter, canlogModeSetConverter, canlogTimeSetConverter });
	}


}
