/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Null;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.LongConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class ParaSetRsp {

	@Null
	@Component(0)
	public Long intSet;	/* OPTIONAL */

	@Null
	@Component(1)
	public Long link1Set;	/* OPTIONAL */

	@Null
	@Component(2)
	public Long link2Set;	/* OPTIONAL */

	@Null
	@Component(3)
	public Long link2EnSet;	/* OPTIONAL */

	@Null
	@Component(4)
	public Long vinSet;	/* OPTIONAL */

	@Null
	@Component(5)
	public Long destSet;	/* OPTIONAL */

	@Null
	@Component(6)
	public Long boundSet;	/* OPTIONAL */

	@Null
	@Component(7)
	public Long dbcNameSet;	/* OPTIONAL */

	@Null
	@Component(8)
	public Long sysSet;	/* OPTIONAL */

	@Null
	@Component(9)
	public Long sdHzSet;	/* OPTIONAL */

	@Null
	@Component(10)
	public Long authKeySet;	/* OPTIONAL */

	@Null
	@Component(11)
	public Long commIntSet;	/* OPTIONAL */

	@Null
	@Component(12)
	public Long canlogModeSet;	/* OPTIONAL */

	@Null
	@Component(13)
	public Long canlogTimeSet;	/* OPTIONAL */


	public boolean equals(Object obj) {
		if(!(obj instanceof ParaSetRsp)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static ParaSetRsp der_decode(InputStream in) throws IOException {
		return (ParaSetRsp)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65547);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(ParaSetRsp.class);
		AsnConverter intSetConverter = LongConverter.INSTANCE;
		AsnConverter link1SetConverter = LongConverter.INSTANCE;
		AsnConverter link2SetConverter = LongConverter.INSTANCE;
		AsnConverter link2EnSetConverter = LongConverter.INSTANCE;
		AsnConverter vinSetConverter = LongConverter.INSTANCE;
		AsnConverter destSetConverter = LongConverter.INSTANCE;
		AsnConverter boundSetConverter = LongConverter.INSTANCE;
		AsnConverter dbcNameSetConverter = LongConverter.INSTANCE;
		AsnConverter sysSetConverter = LongConverter.INSTANCE;
		AsnConverter sdHzSetConverter = LongConverter.INSTANCE;
		AsnConverter authKeySetConverter = LongConverter.INSTANCE;
		AsnConverter commIntSetConverter = LongConverter.INSTANCE;
		AsnConverter canlogModeSetConverter = LongConverter.INSTANCE;
		AsnConverter canlogTimeSetConverter = LongConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { intSetConverter, link1SetConverter, link2SetConverter, link2EnSetConverter, vinSetConverter, destSetConverter, boundSetConverter, dbcNameSetConverter, sysSetConverter, sdHzSetConverter, authKeySetConverter, commIntSetConverter, canlogModeSetConverter, canlogTimeSetConverter });
	}


}
