/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.IntegerConverter;
import org.asnlab.asndt.runtime.conv.LongConverter;
import org.asnlab.asndt.runtime.conv.OctetStringConverter;
import org.asnlab.asndt.runtime.conv.StringConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class VCanDate {

	@NotNull
	@Component(0)
	public String dataType;

	@NotNull
	@Min(1L) @Max(2L)
	@Component(1)
	public Integer dataPort;

	@NotNull
	@Component(2)
	public Long dataID;

	@NotNull
	@Min(8L) @Max(8L)
	@Component(3)
	public Integer dataLen;

	@NotNull
	@Size(min=8, max=8)
	@Component(4)
	public byte[] dataValue;


	public boolean equals(Object obj) {
		if(!(obj instanceof VCanDate)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static VCanDate der_decode(InputStream in) throws IOException {
		return (VCanDate)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65564);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(VCanDate.class);
		AsnConverter dataTypeConverter = StringConverter.INSTANCE;
		AsnConverter dataPortConverter = IntegerConverter.INSTANCE;
		AsnConverter dataIDConverter = LongConverter.INSTANCE;
		AsnConverter dataLenConverter = IntegerConverter.INSTANCE;
		AsnConverter dataValueConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { dataTypeConverter, dataPortConverter, dataIDConverter, dataLenConverter, dataValueConverter });
	}


}
