/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "INTEST"
 */
package com.intest.asn;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.DoubleConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.OctetStringConverter;
import org.asnlab.asndt.runtime.conv.VectorConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class VehiData {

	@NotNull
	@Size(min=16, max=16)
	@Component(0)
	public byte[] dbcMD5;

	@NotNull
	@Size(min=1, max=1000)
	@Component(1)
	public Vector<Double> vehiReport;


	public boolean equals(Object obj) {
		if(!(obj instanceof VehiData)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static VehiData der_decode(InputStream in) throws IOException {
		return (VehiData)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = INTEST.type(65562);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(VehiData.class);
		AsnConverter dbcMD5Converter = OctetStringConverter.INSTANCE;
		AsnConverter vehiReportConverter = new VectorConverter(DoubleConverter.INSTANCE);
		CONV.setComponentConverters(new AsnConverter[] { dbcMD5Converter, vehiReportConverter });
	}


}
