/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "EX2"
 */
package com.intest.test.ex2;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

import javax.validation.constraints.NotNull;

import org.asnlab.asndt.runtime.conv.AnnotationCompositeConverter;
import org.asnlab.asndt.runtime.conv.AsnConverter;
import org.asnlab.asndt.runtime.conv.CompositeConverter;
import org.asnlab.asndt.runtime.conv.EncodingRules;
import org.asnlab.asndt.runtime.conv.LongConverter;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

public class Preamble {

	@NotNull
	@Component(0)
	public Long name;

	@NotNull
	@Component(1)
	public Long sex;

	@NotNull
	@Component(2)
	public Long age;

	@NotNull
	@Component(3)
	public User user;


	public boolean equals(Object obj) {
		if(!(obj instanceof Preamble)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static Preamble der_decode(InputStream in) throws IOException {
		return (Preamble)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = EX2.type(65538);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Preamble.class);
		AsnConverter nameConverter = LongConverter.INSTANCE;
		AsnConverter sexConverter = LongConverter.INSTANCE;
		AsnConverter ageConverter = LongConverter.INSTANCE;
		AsnConverter userConverter = User.CONV;
		CONV.setComponentConverters(new AsnConverter[] { nameConverter, sexConverter, ageConverter, userConverter });
	}


}
